name: Deploy Documentation
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Install ANNchor from git
        run: pip install git+https://github.com/gchq/annchor.git
      - name: Build and Commit docs
        uses: sphinx-notes/pages@master
        with:
          documentation_path: doc
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
